# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://121.196.164.163:3306/kunling?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: sunder
    password: "12ewqdsafd432fdsa"
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5s

logging:
  level:
    com.kunling.scheduling: debug
